before_install:
- pip install Pillow==1.7.8 coveralls
- sudo apt-get install -qq libxml2-dev libxslt-dev
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
env:
  global:
    secure: X1pBwo+oqaTJDgb/K0KYYhx6E0VV53SAPwNmQbiZw1f8PGCoW0/tNfsmz+TP3vwzmGjmGHJDfoXI7FMKGdkeb2X8LxwpxSZ9vwDOrQQNr+U50wN+jE5HFzeKlEVFnImtEaCMnXW6ocMZ5biQj1cNekiXF6N3EPHt2POldAHjqmE=
  matrix:
  - PLONE=4.0
  - PLONE=4.1
  - PLONE=4.2
  - PLONE=4.3 QA=true
language: python
python:
- 2.6
- 2.7
install:
- sed -ie "s#travis-4.x.cfg#travis-$PLONE.x.cfg#" travis.cfg
- python bootstrap.py -c travis.cfg
- bin/buildout -t 5 -Nqc travis.cfg
script:
- bin/test
matrix:
  exclude:
  - env: PLONE=4.0
    python: 2.7
  - env: PLONE=4.1
    python: 2.7
  - env: PLONE=4.2
    python: 2.6
  - env: PLONE=4.3 QA=true
    python: 2.6
after_success: test -v QA && bin/coverage.sh && coveralls || true
